project:
  name: 开发测试环境

spring:
  #数据库相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #这里加上后缀用来防止mysql乱码,serverTimezone=GMT%2b8设置时区
#    url: ENC(dpf1LW8RN2RxMEMtrzBwjMQkqe0OEDbW21Mt8/ZSfsmMuxx7H0U1LBR8lvSMF3vS38w7le+a0xDJLmOaLD3FYe3lOjOCJMfQRnlJ5vEFalPxk8BDJ61sD80S2FU95kjSLTMDqzw/2fqJoq1LEGvuHA==)
    url: jdbc:mysql://47.97.192.116:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: ENC(QmwlqZo9jNAzj9c3NLar5Q==)
    password: ENC(S7sDWB3p9R4hGAc6oXU0m7MOleqpOT6c)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #返回的api接口的配置，全局有效
  jackson:
    default-property-inclusion: non_null #如果某一个字段为null，就不再返回这个字段
    time-zone: GMT+8 #解决时差问题

#url相关配置，这里配置url的基本url
server:
  port: 8080

#jasypt加密的密匙
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7

