project:
  name: 正式环境

spring:
  #数据库相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #这里加上后缀用来防止mysql乱码
    url: jdbc:mysql://47.97.192.116:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: qcl
    password: QiuShi123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #返回的api接口的配置，全局有效
  jackson:
    default-property-inclusion: non_null #如果某一个字段为null，就不再返回这个字段


#url相关配置，这里配置url的基本url
server:
  port: 80

#配置日志,这里配置太过简单，所以一般在外面配置logback.xml来实现日志配置
#logging:
#  pattern:
#    console: "%d - %msg%n" #设置控制台日子输出格式
#  path: /var/log/tomcat
#  level:
#    com.qcl.LoggerTest: debug #设置com.qcl.LoggerTest的日志输出级别

